### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by hsnopi** [MaxRobinsonTheGreat/EvolutionSimulator#2]
THis is very cool. 
UI/UX: 
-clicking or hovering over a legend will highlight all cells of that type
-pause at first appearance of cell type X
-click organism loads organism into a panel to analyze

functionality:
-mating. though I know this is complex
-add heat and cold resistance and an environment, wind, water, etc...
It would be interesting to see how large an organism can grow

Good work here! I've been in IT for 25 years. Happy to chat about this.

**Comment by hsnopi** [comment]
have you seen Primer?
https://www.youtube.com/watch?v=YNMkADpvO4w
great series on various rules of evolution. You may want to take a look.

**Comment by hsnopi** [comment]
for food. have some that eat only living things they have killed and others only dead things. This can hunters vs scavengers

**Comment by hsnopi** [comment]
when evolution happens do the values for reproductions, sight distance, etc evolve? mutate?

**Comment by hsnopi** [comment]
-Fit to viewport screen

**Comment by justingolden21** [comment]
I'd be interested in helping with some UX for the form inputs if you're willing @MaxRobinsonTheGreat

**Comment by MaxRobinsonTheGreat** [comment]
@justingolden21 @hsnopi 
Hi all, this is the repo for the original evolution sim. For the Life Engine please go to this repo: https://github.com/MaxRobinsonTheGreat/EvolutionSimulatorV2

You can request/discuss features in the discussions tab, report bugs with issues, and submit PRs for code improvements. All is welcome+appreciated.
